{% set name = "holoviews" %}
{% set version = "1.14.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holoviews-{{ version }}.tar.gz
  sha256: 8d8d171227e9c9eaadd4b037b3ddaa01055a33bacbdbeb57a5efbd273986665f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
    - pyct >=0.4.4
    - param >=1.7.0
    - setuptools >=30.3.0
    - wheel
  run:
    - python >=2.7
    - colorcet
    - numpy >=1.0
    - panel >=0.8.0
    - pandas >=0.20.0
    - param >=1.9.3,<2.0
    - pyviz_comms >=0.7.4
    # Notebook dependencies
    #- ipython >=5.4.0
    #- notebook
    # Recommended dependencies: IPython Notebook + pandas + matplotlib + bokeh
    #- bokeh >=1.1.0
    #- matplotlib-base >=3

test:
  imports:
    - holoviews
  requires:
    - pip
  commands:
    - pip check
    - holoviews -h

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
