{% set version = "1.10.0" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 685ade8873d32d456baf13d655b7f027f3117808f384a982320867a16a10027b

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - numpy
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
