{% set version = "1.10.4" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: df3d427d8d79f9d4a43f319fba3c8a9db69a64d592345ecbd8422367bcac14b8

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.6.1,<2.0
    - numpy >=1.0
    - matplotlib >=2.1
    - bokeh >=0.12.15
    - jupyter
    - notebook
    - ipython >=5.4.0

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD 3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
