{% set version = "1.6.2" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: v{{version}}.tar.gz
  url: https://github.com/ioam/holoviews/archive/v{{version}}.tar.gz
  sha256: 5162d06cfd1c9b21ea9eac3883e5bae6d06c899d06486105f182df7940b97a21


build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython
    - lancet

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause


extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
