{% set name = "holoviews" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dde3a10bb77aff0982e21786b4f5249c6a9d70c463f5604a49fcf30c0247756

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - holoviews = holoviews.util.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - bokeh >=3.1
    - colorcet
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=2.0,<3.0
    - pyviz_comms >=2.1
    - narwhals >=2
    - python-dateutil >=2.8.2
    - matplotlib-base >=3
    - pyviz-comms >=2.1
  run_constrained:
    - plotly >=4.0
    - matplotlib-base >=3

test:
  imports:
    - holoviews
    - holoviews.core
    - holoviews.core.data
    - holoviews.core.util
    - holoviews.element
    - holoviews.operation
    - holoviews.plotting
    - holoviews.plotting.mpl
    - holoviews.plotting.bokeh
    - holoviews.util
  source_files:
    - holoviews/tests
  requires:
    - pip
    - pytest
    - scipy
  commands:
    - pip check
    - holoviews -h
    - pytest --pyargs holoviews.tests

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
    - hoxbro
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
