{% set name = "holoviews" %}
{% set version = "1.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/holoviews-{{ version }}.tar.gz
  sha256: dec2417f654008b1d7b645b31ecf621c8bef901694e4c4e7272effd18afa36db

build:
  number: 0
  # We cannot build a recent version of panel due to missing nodejs on s390x
  skip: True  # [py<37 or s390x]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - holoviews = holoviews.util.command:main

requirements:
  host:
    - python
    - pip
    - pyct
    - param
    - setuptools
    - wheel
  run:
    - python
    - colorcet
    - numpy >=1.0
    - packaging
    - panel >=0.13.1
    - pandas >=0.20.0
    - param >=1.9.3,<2.0
    - pyviz_comms >=0.7.4
    # Notebook dependencies
    - ipython >=5.4.0
    - notebook
    # Recommended dependencies: IPython Notebook + pandas + matplotlib + bokeh
    # It seems it seems holoviews isn't compatible with bokeh >=3.0.0
    - bokeh >=2.4.3,<3.0
    - matplotlib-base >=3

test:
  imports:
    - holoviews
  requires:
    - pip
  commands:
    - pip check
    - holoviews -h

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
