{% set name = "holoviews" %}
{% set version = "1.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 837885ab2fa376677f21dae0b2a2aeb94ba6db96e9fcb3824cdb899538ee5032

build:
  number: 0
  # We cannot build a recent version of panel due to missing nodejs and panel on s390x
  skip: True  # [py<310]
  entry_points:
    - holoviews = holoviews.util.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python
    - bokeh >=3.1
    - colorcet
    - matplotlib-base >=3.0
    - numpy >=1.21
    - packaging
    - pandas >=1.3
    - panel >=1.0
    - param >=2.0,<3.0
    - pyviz_comms >=2.1
  run_constrained:
    - plotly >=4.0

test:
  imports:
    - holoviews
  requires:
    - pip
  commands:
    - pip check
    - holoviews -h

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
    - hoxbro
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
