{% set version = "1.8.0" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://github.com/ioam/holoviews/archive/v{{version}}.tar.gz
  sha256: a8bd74f0d099a39af059147953785be78662b0b3

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt


requirements:
  build:
    - python
    - param
    - setuptools
  run:
    - python
    - param
    - numpy
    - matplotlib
    - bokeh
    - jupyter
    - notebook
    - ipython
    - lancet

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
