{% set version = "1.10.9" %}

package:
  name: holoviews
  version: {{ version }}

source:
  url: https://assets.holoviews.org/packages/holoviews-1.10.9.tar.gz
  sha256: 07103bff532aad93669e55527e69886aeec1dbf3998ab3eb1b11edb15a146aff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"


requirements:
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.6.1,<2.0
    - numpy >=1.0
    - matplotlib >=2.1
    - bokeh >=0.12.15,<1.1.0
    - jupyter
    - notebook
    - ipython >=5.4.0
    - pyviz_comms

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD 3-Clause
  license_file: LICENSE.txt
  dev_url: https://github.com/ioam/holoviews
  doc_url: http://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
