{% set name = "holoviews" %}
{% set version = "1.23.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97877ee2fcf7bf38ce63f49b731dba75d9b2fcfaf093ca51bd229770a4273cc0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - holoviews = holoviews.util.command:main
  skip: true  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python
    - bokeh >=3.1
    - colorcet
    - narwhals >=2
    - numpy >=1.21
    - pandas >=1.3
    - panel >=1.0
    - param >=2.0,<3.0
    - python-dateutil >=2.8.2
    - pyviz_comms >=2.1
    # optional but recommended
    - matplotlib-base >=3 # base version to not pull qt
  run_constrained:
    - plotly >=4.0

# Skip unstable test 
{% set deselect_tests = " --deselect=util/test_transform.py::TestDimTransforms::test_var_transform" %}
test:
  imports:
    - holoviews
    - holoviews.core
    - holoviews.core.data
    - holoviews.core.util
    - holoviews.element
    - holoviews.operation
    - holoviews.plotting
    - holoviews.plotting.mpl
    - holoviews.plotting.bokeh
    - holoviews.util
  commands:
    - pip check
    - holoviews -h
    - pytest --pyargs --asyncio-mode=auto holoviews.tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - scipy

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
    - hoxbro
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
