{% set name = "holoviews" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 45c568ae57a43af73893a093e6fade96b7713cbb0fe6fff46426a6b613122746

build:
  number: 0
  # We cannot build a recent version of panel due to missing nodejs and panel on s390x
  skip: True  # [py<37 or s390x]
  entry_points:
    - holoviews = holoviews.util.command:main
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - pyct
    - param
    - setuptools
    - wheel
  run:
    - python
    - colorcet
    - numpy >=1.0
    - packaging
    - panel >=0.13.1
    - pandas >=0.20.0
    - param >=1.12.0,<3.0
    - pyviz_comms >=0.7.4
    - matplotlib-base >=3

test:
  imports:
    - holoviews
  requires:
    - pip
  commands:
    - pip check
    - holoviews -h

about:
  home: https://holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  description: |
    HoloViews is an open-source Python library designed to make data analysis
    and visualization seamless and simple. With HoloViews, you can usually
    express what you want to do in very few lines of code, letting you focus on
    what you are trying to explore and convey, not on the process of plotting.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  dev_url: https://github.com/holoviz/holoviews
  doc_url: https://holoviews.org/getting_started/index.html

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
  skip-lints:
    - python_build_tool_in_run
    - host_section_needs_exact_pinnings
