travis:
  secure:
    BINSTAR_TOKEN: DhEdb/xK6GiU7+r4zDvy1AWdI+Zp04EFkPMoeXmgZXnmvo6FaoicC1eWGi8erR+tyCQEZhFkxQ7OFPZ03nk9r+jWWUGSOIvcnEUTsbvu2oipHiolKT/gEY/lBiq2j1Yw07ygU1eZ0FnbKG9Jh8ax+kna3eT2n3E3YbjUZ6ijjo7VMJxg0yRUAimGp5b6QitI9vV9tynBpJIbQOXityC0Zu3+vN2ZEvomE+F/7anynXDgXKySVfehoz4YY3zzkcmlwIki+ro6uqiCbY+PMi4BD4eCzMhp7k5vPM/GTdHE9/cVENClJx4RWV/AXG3oCSief7arOuDs03VMye9TwtdwZTwx5hzpCAxQPf5R3/3q1ojRQNLMhFMZPWjs33sLO9x9/9j/NapjIwTdwrlwAXv7KVqvd4iDoKvjjJEIz++HmVbbCj2Vcg8VUWZanwBw5+3mWzjQjvLVcEEsTFKtRvbe8suTk6LI53lq6ZWcx4xEyCRBH2yNmy+4ZxwCF2/Mvzp6cZj+rxgL4+QjOjSWt3oU/TKGrd6TxG5ya+nwo9ZJdRxwZD+OvYnB0Ec+bszoom/6XowAQ0HySJ3AeA4KKFDfj7+tBPKCEL7jAL9PWuHKbZAp2J6IKyrQLTcpeQwqOBzv9nakhqtky8X6OhvQ42kU1S9E8Z27l2Q3esR/7QFqaCU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
